name: ChunkClaimPlugin
version: 1.0
main: ashinmc.myfirstplugin.Main
api-version: 1.20
commands:
  claimchunk:
    description: Claim the chunk you are standing in.
  unclaimchunk:
    description: Unclaim the chunk you are standing in.
  checkchunk:
    description: Check the ownership of the chunk you are standing in.
  infochunk:
    description: Get a list of your claimed chunks.
  visualizechunk:
    description: Visualize the borders of the chunk you are standing in.
